### ISSUE TITLE
Anzeige von Isttemperatur und Luftfeuchtigkeit

### ISSUE THREAD

**Issue by cjh2** [ifavo/MaxStats#1]
Hallo,

ich habe gesehen dass im cube JEQ0193016 auf der Maxstats Seite die Isttemperatur und Luftfeuchtigkeit in allen Räumen angezeigt werden. Wie wird das denn gemacht.

Gruß
Claus

**Comment by ifavo** [comment]
Für den Cube habe ich eine Ausnahme hinterlegt, das die Außentemperatur und Luftfeuchtigkeit hinein geladen wird.

Du kannst die Ausnahme hier sehen:
https://github.com/ifavo/MaxStats/blob/master/application/views/scripts/index/dashboard.phtml#L61-L63

Hinter der Geräte-ID versteckt sich ein Außenthermometer :-)
